### ISSUE TITLE
MIMETYPE!?

### ISSUE THREAD

**Issue by blaasvaer** [Neos21/in-browser-sass#2]
I get this error, whatever I set in "type" (type="text/sass", type="text/scss" or type="text/css"):
```
The stylesheet http://grid2fullscreen.local/css/style.scss was not loaded because its MIME type, “text/plain”, is not “text/css”.
```

**Comment by rafegoldberg** [comment]
I'm also getting this issue, but _only_ in Firefox (v72 on macOS). E'erything works fine in Chrome (v79) though! Any thoughts on how best to resolve this issue @Neos21?
