### ISSUE TITLE
OK, this is a complete mess trying to get to work!

### ISSUE THREAD

**Issue by blaasvaer** [Neos21/in-browser-sass#3]
Could you provide a simple working example for download, as I can't seem to get ANYTHING of this to work?

**Comment by rafegoldberg** [comment]
Not trying to be a dick but this type of comment is really _not_ useful, @blaasvaer. When opening new issues, you should be concise and clear and always try to provide clear reproduction steps, error messages etc. Just shouting "THIS IS BROKEN" is unlikely to net you any useful answers or brownie points from the repo's maintainer.
