### ISSUE TITLE
Syntax errors?

### ISSUE THREAD

**Issue by blaasvaer** [Neos21/in-browser-sass#4]
I get this as well:

```
SyntaxError: expected expression, got '&'
```
from the "in-browser-sass-standalone.min.js" file ...

**Comment by rafegoldberg** [comment]
Yeah @blaasvaer, I also noticed that the standalone build doesn't seem to work... but following the initial instructions under the **Installation** section should sort this out for ya:

```html
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.10.7/sass.sync.min.js"></script>
  <script src="in-browser-sass.min.js"></script>
  <link href="./main.scss" type="text/scss" rel="stylesheet">
</head>
```

(Also, pro tip: if you don't have a copy of the `in-browser-sass.js` file, you can reference the raw file directly from GitHub using this URL:

```
https://raw.githack.com/Neos21/in-browser-sass/master/in-browser-sass.min.js
```
